config/routes.rb
EduCMS::Application.routes.draw do

  resources :grades

  resources :surveys

  resources :messages

  resources :documents

  resources :subjects

  resources :categories

  resources :groups

  resources :news

  resources :password_resets

  resources :user_sessions

  resources :users do
    member do
      get :activate
    end
  end

  resources :surveys do
    member do
      get :testing
    end
  end

  resources :users do
    member do
      get :grades
    end
  end

  resources :surveys do
    member do
      get :grades
    end
  end

  resources :subjects do
    member do
      get :grades
    end
  end

  resources :groups do
    member do
      get :grades
    end
  end

  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"

  match '/about'                  => 'home#about'
  match '/contacts'               => 'home#contacts'
  match '/index'                  => 'news#index'
  match '/signup'                 => 'users#new'
  match '/learn'                  => 'documents#index'
  match '/help'                   => 'help#index'
  match '/help/markup'            => 'help#markup'
  match '/help/administration'    => 'help#administration'
  match '/admin'                  => 'admin#index'
  match '/admin/criteria'         => 'admin#criteria'
  match 'internal_server_error'   => 'errors#internal_server_error'
  match 'not_found'               => 'errors#not_found'
  match 'unprocessable_entity'    => 'errors#unprocessable_entity'

  match 'login'   => 'user_sessions#new',     :as => :login
  match 'logout'  => 'user_sessions#destroy', :as => :logout
  match 'inbox'   => 'messages#inbox',        :as => :inbox
  match 'outbox'  => 'messages#outbox',       :as => :outbox

  root :to => "news#index"

end

app/views/admin/criteria.html.erb
<div class='title'>
  <hr />
  <h1>Критерии оценок</h1>
  <hr />
</div>

<div class='white_container round'>
  <font color='red'>Внимание!</font> Пожалуйста, используйте следующую функциональность с осторожностью.<br />
  Оценку определяет процентное соотношение верных ответов и общего их количества.<br />
  Задаются они путём определения нижней и верхней границ для оценок.<br />
  Например, для пятерки это может быть 90 - 100.
  <%= form_tag admin_criteria_path, :method => 'get' do %>
    Пятёрка: <%= text_field_tag :five_bottom, params[:five_bottom] %> - <%= text_field_tag :five_top, params[:five_top] %><br />
    Четверка: <%= text_field_tag :four_bottom, params[:four_bottom] %> - <%= text_field_tag :four_top, params[:four_top] %><br />
    Тройка: <%= text_field_tag :three_bottom, params[:three_bottom] %> - <%= text_field_tag :three_top, params[:three_top] %><br />
    <%= submit_tag 'Сохранить', :name => nil  %>
  <% end %>
</div>

app/views/admin/index.html.erb
<div class='title'>
  <hr />
  <h1>Страница администрирования</h1>
  <hr />
</div>

<div class='white_container round'>

  <h2>Скрытые разделы:</h2>
  <div class='box'>
    <%= link_to "Категории", categories_path %>
  </div>
  <div class='box'>
    <%= link_to "Предметы", subjects_path %>
  </div>
  <div class='box'>
    <%= link_to "Группы", groups_path %>
  </div>
  <hr class='clear' />

  <div class='text'>
  <h2>Информация:</h2>
  Сейчас онлайн:
  <% current_users_list.each do |user| %>
    <%= link_to user.username, user %><%= ',' if current_users_list.size > 1 %>
  <% end %>
  <br />
  Список администраторов:
  <% @admins.each do |admin| %>
    <%= link_to admin.username, admin %><%= ',' if @admins.size > 1 %>
  <% end %>

<!--  <hr class='clear' />
  <h2>Функции:</h2>
  <%= link_to "Измение критериев оценок за тесты", admin_criteria_path %>
  </div>-->

</div>