config/routes.rb
EduCMS::Application.routes.draw do

  resources :grades

  resources :surveys

  resources :messages

  resources :documents

  resources :subjects

  resources :categories

  resources :groups

  resources :news

  resources :password_resets

  resources :user_sessions

  resources :users do
    member do
      get :activate
    end
  end

  resources :surveys do
    member do
      get :testing
    end
  end

  resources :users do
    member do
      get :grades
    end
  end

  resources :surveys do
    member do
      get :grades
    end
  end

  resources :subjects do
    member do
      get :grades
    end
  end

  resources :groups do
    member do
      get :grades
    end
  end

  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"

  match '/about'                  => 'home#about'
  match '/contacts'               => 'home#contacts'
  match '/index'                  => 'news#index'
  match '/signup'                 => 'users#new'
  match '/learn'                  => 'documents#index'
  match '/help'                   => 'help#index'
  match '/help/markup'            => 'help#markup'
  match '/help/administration'    => 'help#administration'
  match '/admin'                  => 'admin#index'
  match '/admin/criteria'         => 'admin#criteria'
  match 'internal_server_error'   => 'errors#internal_server_error'
  match 'not_found'               => 'errors#not_found'
  match 'unprocessable_entity'    => 'errors#unprocessable_entity'

  match 'login'   => 'user_sessions#new',     :as => :login
  match 'logout'  => 'user_sessions#destroy', :as => :logout
  match 'inbox'   => 'messages#inbox',        :as => :inbox
  match 'outbox'  => 'messages#outbox',       :as => :outbox

  root :to => "news#index"

end

app/models/group.rb
# coding: utf-8

# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

class Group < ActiveRecord::Base
  has_many :documents, :dependent => :restrict
  has_many :users, :dependent => :restrict
  has_many :surveys, :dependent => :restrict

  validates :title, :presence => { :message => "Не должно быть пустым" },
      :length => { :maximum => 80, :too_long  => "Должен составлять не более %{count} символов" }

  ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
    if instance.error_message.kind_of?(Array)
      html = ""
      instance.error_message.each do |string|
        html << "<li class='validation-error' style='color: red;'>#{string}</li>" unless string == "can't be blank"
      end
      %(#{html_tag}<ul>
      #{html}</ul>).html_safe
    else
      %(#{html_tag}<span class="validation-error" style='color: red;'>
      #{instance.error_message}</span>).html_safe
    end
  end

  self.per_page = 10
end

app/controllers/groups_controller.rb
# coding: utf-8

# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

class GroupsController < ApplicationController

  before_filter :admin?

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.paginate(:page => params[:page])
    @title = "Группы"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @title = "Группа: " << @group.title

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
    @title = "Новая группа"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    @title = "Группа: " << @group.title
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Группа добавлена.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Группа изменена.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    begin
      @group.destroy
    rescue ActiveRecord::DeleteRestrictionError
      error = 'Эта группа не может быть удалена, пока с ней связан хоть один файл, пользователь или тест.'
    ensure
      respond_to do |format|
        format.html { redirect_to groups_url, notice: error }
        format.json { head :ok }
      end
    end
  end

  def grades
    @grades = []
    Group.find(params[:id]).surveys.each { |x| @grades << x.grades }
    @grades.flatten!
    @title = "Оценки"
    respond_to do |format|
      format.html
      format.json { render json: @grades }
    end
  end

end

app/helpers/groups_helper.rb
# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <div class="field">
    <%= f.label "Название" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='white_container round'>
  <%= render 'form' %>
  <div class='box'>
    <%= link_to 'Назад', groups_path %>
  </div>
</div>

app/views/groups/grades.html.erb
<div class='title'>
  <hr />
  <h1>Оценки</h1>
  <hr />
</div>

<div class='white_container round'>
  <table>
    <tr>
      <th><%= link_to "Пользователь",   :sort => "user"       %></th>
      <th><%= link_to "Тест",           :sort => "survey"     %></th>
      <th><%= link_to "Оценка",         :sort => "mark"       %></th>
      <th><%= link_to "Процент",        :sort => "percentage" %></th>
      <th><%= link_to "Верных ответов", :sort => "right"      %></th>
      <th><%= link_to "Вопросов",       :sort => "questions"  %></th>
    </tr>

    <% @grades.each do |grade| %>
      <tr>
        <td><%= link_to grade.user.username, grade.user %></td>
        <td><%= link_to grade.survey.title, grade.survey  %></td>
        <td><%= grade.mark %></td>
        <td><%= grade.percentage %></td>
        <td><%= grade.right %></td>
        <td><%= grade.questions %></td>
      </tr>
    <% end %>
  </table>
</div>

<br />

app/views/groups/index.html.erb
<div class='title'>
  <hr />
  <h1>Группы</h1>
  <% if admin?  %>
    <div class='action'><%= link_to 'Создать группу', new_group_path, :class => 'button' %></div>
  <% end %>
  <hr />
</div>

<% @groups.each do |group| %>
  <div class='white_container round'>
    <%= link_to group.title, group %>
    <% if admin? %>
      <p>
<!--    <div class='box'>
          <%= link_to 'Оценки', grades_group_path(group) %>
        </div>style='color: gray; display: inline; float: right;'-->
        <div>
          <div class='box'>
            <%= link_to 'Редактировать', edit_group_path(group) %>
          </div>
          <div class='box'>
            <%= link_to 'Удалить', group, confirm: 'Вы уверены?', method: :delete %>
          </div> 
        </div>
      </p>
    <% end %>
  </div>  
<% end %>

<hr />
  <%= will_paginate @groups %>
<hr />

app/views/groups/new.html.erb
<div class='white_container round'>
  <%= render 'form' %>
  <div class='box'>
    <%= link_to 'Назад', groups_path %>
  </div>
</div>

app/views/groups/show.html.erb
<div class='white_container round'>
  <p>
    <b>Название:</b>
    <%= @group.title %>
  </p>
  <div class='box'>
    <%= link_to 'Редактировать', edit_group_path(@group) %>
  </div>
  <div class='box'>
    <%= link_to 'Назад', groups_path %>
  </div>
</div>