config/routes.rb
EduCMS::Application.routes.draw do

  resources :grades

  resources :surveys

  resources :messages

  resources :documents

  resources :subjects

  resources :categories

  resources :groups

  resources :news

  resources :password_resets

  resources :user_sessions

  resources :users do
    member do
      get :activate
    end
  end

  resources :surveys do
    member do
      get :testing
    end
  end

  resources :users do
    member do
      get :grades
    end
  end

  resources :surveys do
    member do
      get :grades
    end
  end

  resources :subjects do
    member do
      get :grades
    end
  end

  resources :groups do
    member do
      get :grades
    end
  end

  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"

  match '/about'                  => 'home#about'
  match '/contacts'               => 'home#contacts'
  match '/index'                  => 'news#index'
  match '/signup'                 => 'users#new'
  match '/learn'                  => 'documents#index'
  match '/help'                   => 'help#index'
  match '/help/markup'            => 'help#markup'
  match '/help/administration'    => 'help#administration'
  match '/admin'                  => 'admin#index'
  match '/admin/criteria'         => 'admin#criteria'
  match 'internal_server_error'   => 'errors#internal_server_error'
  match 'not_found'               => 'errors#not_found'
  match 'unprocessable_entity'    => 'errors#unprocessable_entity'

  match 'login'   => 'user_sessions#new',     :as => :login
  match 'logout'  => 'user_sessions#destroy', :as => :logout
  match 'inbox'   => 'messages#inbox',        :as => :inbox
  match 'outbox'  => 'messages#outbox',       :as => :outbox

  root :to => "news#index"

end

app/models/document.rb
# coding: utf-8

# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

require 'where'

class Document < ActiveRecord::Base
  mount_uploader :file, FileUploader
  belongs_to :category
  belongs_to :group
  belongs_to :subject

  validates :title, :presence => { :message => "Не должно быть пустым" },
      :length => { :maximum => 150, :too_long  => "Должен составлять не более %{count} символов" }

  ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
    if instance.error_message.kind_of?(Array)
      html = ""
      instance.error_message.each do |string|
        html << "<li class='validation-error' style='color: red;'>#{string}</li>" unless string == "can't be blank"
      end
      %(#{html_tag}<ul>
      #{html}</ul>).html_safe
    else
      %(#{html_tag}<span class="validation-error" style='color: red;'>
      #{instance.error_message}</span>).html_safe
    end
  end

  def self.search(category, subject, group, keywords)
    condition = Where.new
    condition.and('title like ? OR descryption like ?', "%#{keywords}%",  "%#{keywords}%") unless keywords.blank?
    condition.and('category_id = ?', category) unless category.blank?
    condition.and('group_id = ?', group) unless group.blank?
    condition.and('subject_id = ?', subject) unless subject.blank?
    unless condition.blank?
      where(condition.to_s).order('id DESC')
    else
      order('id DESC')
    end
  end

  self.per_page = 10
end

app/controllers/documents_controller.rb
# coding: utf-8

# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

class DocumentsController < ApplicationController

  before_filter :admin?, :only => [:edit, :new, :create, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @title = "Файлы"
    unless params[:group]
      @documents = Document.paginate(:page => params[:page]).order('id DESC')
    else
      @documents = Document.search(params[:category], params[:subject],
        params[:group], params[:search]).paginate(:page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])
    @title = @document.title

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new
    @title = "Новый файл"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    @title = @document.title
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Файл добавлен.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Файл изменен.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :ok }
    end
  end
end

app/helpers/documents_helper.rb
# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for @document, :html => {:multipart => true} do |f| %>
  <div class="field">
    <%= f.label "Название" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Описание" %><br />
    <%= f.text_area :descryption %>
  </div>
  <hr class='clear' />
  <table border="1">
    <tr>
      <th><%= link_to "Категория:", categories_path %></th>
      <th><%= link_to "Предмет:", subjects_path %></th>
      <th><%= link_to "Группа:", groups_path %></th>
    </tr>
    <tr>
      <td><%= f.select(:category_id, options_from_collection_for_select(Category.all, 'id', 'title', @document.category_id)) %></td>
      <td><%= f.select(:subject_id, options_from_collection_for_select(Subject.all, 'id', 'title', @document.subject_id)) %></td>
      <td><%= f.select(:group_id, options_from_collection_for_select(Group.all, 'id', 'title', @document.group_id)) %></td>
    </tr>
  </table>
  <hr class='clear' />
  <p>
    <%= label_tag "Файл" %>
  </p>
  <%= f.file_field "file" %>
  <%= f.hidden_field :file_cache %>
  <hr class='clear' />
  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<div class='white_container round'>
  <%= render 'form' %>
  <div class='box'>
    <%= link_to 'Показать', @document %>
  </div>
  <div class='box'>
    <%= link_to 'Назад', documents_path %>
  </div>
</div>

app/views/documents/index.html.erb
<div class='title'>
  <hr />
  <h1>Файлы</h1>
  <% if admin?  %>
    <div class='action'><%= link_to 'Добавить файл', new_document_path, :class => 'button' %></div>
  <% end %>
  <hr />
</div>

<%= form_tag documents_path, :method => 'get' do %>
  <%= select_tag 'category', options_from_collection_for_select(Category.all, 'id', 'title', params['category']), { :prompt => 'Категория' } %>
  <%= select_tag 'subject', options_from_collection_for_select(Subject.all, 'id', 'title', params['subject']), { :prompt => 'Предмет' } %>
  <%= select_tag 'group', options_from_collection_for_select(Group.all, 'id', 'title', params['group']), { :prompt => 'Группа' } %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Искать", :name => nil  %>
<% end %>

<% @documents.each do |document| %>
  <div class='white_container round'>
    <div class='box' style='display: inline; float: right;'>
      <%= link_to 'Скачать', document.file.url %>
    </div>
    <h3><%= link_to truncate(document.title, :length => 80, :separator => '…'), document %></h3>
    <div class='text'>
      <%= RedCloth.new(truncate(document.descryption, :length => 300, :separator => '…'), [:filter_html]).to_html.html_safe %>
    </div>
    <div class='box'>
      <%= document.category.title %>
    </div>
    <div class='box'>
      <%= document.subject.title %>
    </div>
    <div class='box'>
      <%= document.group.title %>
    </div>
    <div class='box'>
      <%= document.created_at %>
    </div>
    <% if admin? %>
      <div style='color: gray; display: inline; float: right;'>
        <div class='box'>
          <%= link_to 'Редактировать', edit_document_path(document) %></td>
        </div>
        <div class='box'>
          <%= link_to 'Удалить', document, confirm: 'Are you sure?', method: :delete %></td>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<hr />
  <%= will_paginate @documents %>
<hr />

app/views/documents/new.html.erb
<div class='white_container round'>
  <%= render 'form' %>
  <div class='box'>
    <%= link_to 'Назад', documents_path %>
  </div>
</div>

app/views/documents/show.html.erb
<div class='white_container round'>
  <div class='box' style='display: inline; float: right;'>
    <%= link_to 'Скачать файл', @document.file.url %>
  </div>
  <p style='font-weight: bold;'><%= @document.title %></p>
  <div class='text'>
    <%= RedCloth.new(@document.descryption, [:filter_html]).to_html.html_safe %>
  </div>
  <cpan style='color: gray;'>
    <%= @document.category.title %> |
    <%= @document.subject.title %> |
    <%= @document.group.title %>
  </cpan>
  <div class='clear'>
    <% if admin? %>
      <div class='box'>
        <%= link_to 'Редактировать', edit_document_path(@document) %>
      </div>
    <% end %>
    <div class='box'>
      <%= link_to 'Назад', documents_path %>
    </div>
  </div>
</div>