config/routes.rb
EduCMS::Application.routes.draw do

  resources :grades

  resources :surveys

  resources :messages

  resources :documents

  resources :subjects

  resources :categories

  resources :groups

  resources :news

  resources :password_resets

  resources :user_sessions

  resources :users do
    member do
      get :activate
    end
  end

  resources :surveys do
    member do
      get :testing
    end
  end

  resources :users do
    member do
      get :grades
    end
  end

  resources :surveys do
    member do
      get :grades
    end
  end

  resources :subjects do
    member do
      get :grades
    end
  end

  resources :groups do
    member do
      get :grades
    end
  end

  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"

  match '/about'                  => 'home#about'
  match '/contacts'               => 'home#contacts'
  match '/index'                  => 'news#index'
  match '/signup'                 => 'users#new'
  match '/learn'                  => 'documents#index'
  match '/help'                   => 'help#index'
  match '/help/markup'            => 'help#markup'
  match '/help/administration'    => 'help#administration'
  match '/admin'                  => 'admin#index'
  match '/admin/criteria'         => 'admin#criteria'
  match 'internal_server_error'   => 'errors#internal_server_error'
  match 'not_found'               => 'errors#not_found'
  match 'unprocessable_entity'    => 'errors#unprocessable_entity'

  match 'login'   => 'user_sessions#new',     :as => :login
  match 'logout'  => 'user_sessions#destroy', :as => :logout
  match 'inbox'   => 'messages#inbox',        :as => :inbox
  match 'outbox'  => 'messages#outbox',       :as => :outbox

  root :to => "news#index"

end

app/models/survey.rb
# coding: utf-8

# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

class Survey < ActiveRecord::Base
  belongs_to :group
  belongs_to :subject
  has_many :grades, :dependent => :destroy
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  def estimate(hash, user_id)
    answers = {}
    error = false
    correct = 0
    persent = 0
    mark = 0
    questions_count = questions.size

    # answers: { "question_id" => [ "answer_id", "answer_id" ] }, for exmpl: {"5"=>["11", "13"]}
    hash.each_key do |key|
      unless answers[ key[/\d+/] ]
        answers[ key[/\d+/] ] = [ key[/_\d+/].sub("_", "") ]
      else
        answers[ key[/\d+/] ] = answers[ key[/\d+/] ] + [ key[/_\d+/].sub("_", "") ]
      end
    end

    answers.each_key do |question_id|
      real_answers = Question.find_by_id( question_id ).answers.where( :checked => true )
      if real_answers.size == answers[ question_id ].size then
        real_answers.each do |x|
          unless answers[ question_id ].include?( x.id.to_s ) then
            error = true
            break
          end
        end
        unless error
          correct += 1
        else
          error = false
        end
      end
    end

    persent = 100 * correct / questions_count

    case persent
    when 90..100
      mark = 5
    when 75..90
      mark = 4
    when 60..75
      mark = 3
    else
      mark = 2
    end

    return Grade.create(:user_id => user_id, :survey_id => id, :mark => mark, :percentage => persent.to_f, :questions => questions_count, :right => correct)
  end

end

app/controllers/surveys_controller.rb
# coding: utf-8

# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

class SurveysController < ApplicationController

  before_filter :admin?, :only => [:edit, :new, :create, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.paginate(:page => params[:page])
    @title = "Тесты"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])
    @title = @survey.title

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  def testing
    @survey = Survey.find(params[:id])
    @title = @survey.title

    if params[:utf8] then
      result = @survey.estimate( params.select { |k,v| k =~ /\d+_\d+/ }, current_user.id )
      respond_to do |format|
        format.html { redirect_to grades_user_path(current_user) }
        format.json { render json: @survey }
      end
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @survey }
      end
    end

  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new
    @title = "Новый тест"

    3.times do
      question = @survey.questions.build
      4.times { question.answers.build }
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
    @title = @survey.title
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Тест добавлен.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Тест обновлён.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :ok }
    end
  end

  def grades
    @grades = Survey.find(params[:id]).grades
    @title = "Оценки"
    respond_to do |format|
      format.html
      format.json { render json: @grades }
    end
  end

end

app/helpers/surveys_helper.rb
# Copyright (C) 2011-2012 Vladislav Mileshkin
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

module SurveysHelper
end

app/views/surveys/_answer_fields.html.erb
<div class="field">
  <%= f.link_to_remove "Удалить ответ" %>
  <%= f.label :content, "Ответ:" %>
  <%= f.text_field :content %>
  <%= f.check_box :checked %>
  Верный
</div>

app/views/surveys/_form.html.erb
<%= nested_form_for @survey do |f| %>
<!--<%= f.error_messages %>-->
  <div class="field">
    <%= f.label "Название" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Описание" %><br />
    <%= f.text_area :descryption %>
  </div>
  <table border="1">
    <tr>
      <th><%= link_to "Предмет:", subjects_path %></th>
      <th><%= link_to "Группа:", groups_path %></th>
    </tr>
    <tr>
      <td><%= f.select :subject_id, options_from_collection_for_select(Subject.all, 'id', 'title', @survey.subject_id) %></td>
      <td><%= f.select :group_id, options_from_collection_for_select(Group.all, 'id', 'title', @survey.group_id) %></td>
    </tr>
  </table>
  <hr class='clear' />

  <%= f.fields_for :questions %>

  <%= f.link_to_add "Добавить вопрос", :questions %>

  <div class='clear'>
    <%= f.submit "Сохранить" %>
  </div>

  <div class='clear'>
    <hr />
  </div>

<% end %>

app/views/surveys/_question_fields.html.erb
<div class="field">
  <%= f.label :content, "Вопрос:" %><br />
  <%= f.text_area :content, :class => "question" %><br />
  <%= f.link_to_remove "Удалить вопрос" %>
</div>
<%= f.fields_for :answers %>
<p><%= f.link_to_add "Добавить ответ", :answers %></p>

app/views/surveys/edit.html.erb
<div class='white_container round'>
  <%= render 'form' %>
  <div class='box'>
    <%= link_to 'Показать', @survey %>
  </div>
  <div class='box'>
    <%= link_to 'Назад', surveys_path %>
  </div>
</div>

app/views/surveys/grades.html.erb
<div class='title'>
  <hr />
  <h1>Оценки</h1>
  <hr />
</div>

<div class='white_container round'>
  <table>
    <tr>
      <th><%= link_to "Пользователь",   :sort => "user"       %></th>
      <th><%= link_to "Тест",           :sort => "survey"     %></th>
      <th><%= link_to "Оценка",         :sort => "mark"       %></th>
      <th><%= link_to "Процент",        :sort => "percentage" %></th>
      <th><%= link_to "Верных ответов", :sort => "right"      %></th>
      <th><%= link_to "Вопросов",       :sort => "questions"  %></th>
    </tr>

    <% @grades.each do |grade| %>
      <tr>
        <td><%= link_to grade.user.username, grade.user %></td>
        <td><%= link_to grade.survey.title, grade.survey  %></td>
        <td><%= grade.mark %></td>
        <td><%= grade.percentage %></td>
        <td><%= grade.right %></td>
        <td><%= grade.questions %></td>
      </tr>
    <% end %>
  </table>
</div>

<br />

app/views/surveys/index.html.erb
<div class='title'>
  <hr />
  <h1>Тесты</h1><sup>beta</sup>
  <% if admin?  %>
    <div class='action'><%= link_to 'Создать тест', new_survey_path, :class => 'button' %></div>
  <% end %>
  <hr />
</div>

<% @surveys.each do |survey| %>
<div class='white_container round'>
  <div class='box' style='display: inline; float: right;'>
    <%= link_to "Оценки", grades_survey_path(survey) %>
  </div>
  <h3><%= link_to truncate(survey.title, :length => 80, :separator => '...'), survey %></h3>
  <div class='text'>
    <%= RedCloth.new(truncate(survey.descryption, :length => 300, :separator => '...'), [:filter_html]).to_html.html_safe %>
  </div>
  <div class='box'>
    <%= survey.subject.title %>
  </div>
  <div class='box'>
    <%= survey.group.title %>
  </div>
  <% if admin? %>
    <cpan style='float: right;'>
    <div class='box'>
      <%= link_to 'Редактировать', edit_survey_path(survey) %>
    </div>
    <div class='box'>
      <%= link_to 'Удалить', survey, confirm: 'Вы уверены?', method: :delete %>
    </div>
    </cpan>
  <% end %>
</div>
<% end %>

<hr />
  <%= will_paginate @surveys %>
<hr />

app/views/surveys/new.html.erb
<div class='white_container round'>
  <%= render 'form' %>
  <div class='box'>
    <%= link_to 'Назад', surveys_path %>
  </div>
</div>

app/views/surveys/show.html.erb
<div class='white_container round'>

  <p style='font-weight: bold;'><%= @survey.title %></p>
  <div class='text'>
    <%= RedCloth.new(@survey.descryption, [:filter_html]).to_html.html_safe %>
  </div>
  <cpan style='color: gray;'>
    <%= @survey.subject.title %> |
    <%= @survey.group.title %>
  </cpan>
  <hr />

  <% if admin? %>
    <div class='clear'>
      <ol>
        <% for question in @survey.questions %>
          <li>
            <%= question.content %>
            <ul>
              <% for answer in question.answers %>
                <li><%= answer.content %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ol>
    </div>

    <div class='box'>
      <%= link_to 'Редактировать', edit_survey_path(@survey) %>
    </div>
  <% end %>

  <div class='box'>
    <%= link_to 'Пройти тест', testing_survey_path(@survey) %>
  </div>

  <div class='box'>
    <%= link_to 'Назад', surveys_path %>
  </div>

</div>

app/views/surveys/testing.html.erb
<div class='white_container round'>

  <p style='font-weight: bold;'>
    <%= @survey.title %>
  </p>
  <div class='text'>
    <%= RedCloth.new(@survey.descryption, [:filter_html]).to_html.html_safe %>
  </div>
  <hr />

  <div class='clear'>
    <%= form_tag testing_survey_path(@survey), :method => 'get' do |testing_form| %>
      <ol>
        <% for question in @survey.questions %>
          <li>
            <%= question.content %>
            <ul>
              <% for answer in question.answers %>
                <%= check_box_tag(question.id.to_s << "_" << answer.id.to_s) %>
                <%= answer.content %>
                <br />
              <% end %>
            </ul>
          </li>
        <% end %>
      </ol>
      <%= submit_tag "Завешить тест", :name => nil  %>
    <% end %>
  </div>

  <div class='box'>
    <%= link_to 'Отменить', survey_path %>
  </div>

</div>